version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10-browsers

aliases:
  - &restore_cache
    restore_cache:
      keys:
        - v2.1-dependencies-{{ checksum "package-lock.json" }}
  - &filter-only-master
    branches:
      only:
        - master
  - &authenticate_npm
    run:
      name: Authenticate with npm
      command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
  - &add_ssh_key
    add_ssh_keys:
      fingerprints:
        - '03:18:ba:47:c7:56:bf:4e:2f:90:ea:5a:b0:42:99:5a'

  - &authenticate_git
    run:
      name: Authenticate with git
      command: git config user.email "circleci@eurosport.com" && git config user.name "CircleCI"
  - &slack_notification
    run:
      name: Slack notification
      command: node ./.circleci/deploymentNotification.js

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/Cypress
          key: v2.1-dependencies-{{ checksum "package-lock.json" }}
  test_unit:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm run test:ci
      - persist_to_workspace:
          root: .
          paths:
            - coverage/*
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm run build
  lint:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm run lint
  sonarcloud:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run sonarCloud
          command: |
            export SONAR_SCANNER_VERSION=3.3.0.1492
            export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION
            rm -rf $SONAR_SCANNER_HOME
            mkdir -p $SONAR_SCANNER_HOME
            curl -sSLo $HOME/.sonar/sonar-scanner.zip http://repo1.maven.org/maven2/org/sonarsource/scanner/cli/sonar-scanner-cli/$SONAR_SCANNER_VERSION/sonar-scanner-cli-$SONAR_SCANNER_VERSION.zip
            unzip $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
            rm $HOME/.sonar/sonar-scanner.zip
            export PATH=$SONAR_SCANNER_HOME/bin:$PATH
            export SONAR_SCANNER_OPTS="-server"
            curl -L https://git.io/n-install | N_PREFIX=~/util/n bash -s -- -y 10.12.0
            export PATH=/home/circleci/util/n/bin:$PATH
            node -v
            sonar-scanner \
             -Dsonar.projectKey=EurosportDigital_web-toolkit \
             -Dsonar.organization=eurosportdigital \
             -Dsonar.sources=./src \
             -Dsonar.branch.name=$CIRCLE_BRANCH \
             -Dsonar.host.url=https://sonarcloud.io \
             -Dsonar.login=$SONAR_CLOUD_LOGIN \
             -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info \

  test_cypress:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm run build-storybook
      - run:
          command: npm run start-static-storybook
          background: true
      - run: ./node_modules/.bin/wait-on http://localhost:5000
      - run: npm run cypress
      - store_artifacts:
          path: ./cypress/screenshots/
  npm_patch:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *authenticate_npm
      - *add_ssh_key
      - *authenticate_git
      - run: npm version patch -m "%s [skip ci]"
      - run: npm publish
      - run: git push
      - *slack_notification
  npm_minor:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *authenticate_npm
      - *add_ssh_key
      - *authenticate_git
      - run: npm version minor -m "%s [skip ci]"
      - run: npm publish
      - run: git push
      - *slack_notification
  npm_major:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *authenticate_npm
      - *add_ssh_key
      - *authenticate_git
      - run: npm version major -m "%s [skip ci]"
      - run: npm publish
      - run: git push
      - *slack_notification

workflows:
  version: 2
  build_and_test:
    jobs:
      - dependencies
      - test_cypress:
          requires:
            - dependencies
      - test_unit:
          requires:
            - dependencies
      - build:
          requires:
            - dependencies
      - lint:
          requires:
            - dependencies
      - sonarcloud:
          requires:
            - test_unit
      - qa_validation:
          type: approval
          requires:
            - test_unit
            - test_cypress
            - lint
            - build
      - run_npm_patch:
          type: approval
          requires:
            - qa_validation
          filters: *filter-only-master
      - npm_patch:
          requires:
            - run_npm_patch
          filters: *filter-only-master
      - run_npm_minor:
          type: approval
          requires:
            - qa_validation
          filters: *filter-only-master
      - npm_minor:
          requires:
            - run_npm_minor
          filters: *filter-only-master
      - run_npm_major:
          type: approval
          requires:
            - qa_validation
          filters: *filter-only-master
      - npm_major:
          requires:
            - run_npm_major
          filters: *filter-only-master
