export const rounds = [
  {
    id: 5048,
    name: '1er tour',
    number: 1,
  },
  {
    id: 5041,
    name: '2e tour',
    number: 2,
  },
  {
    id: 5038,
    name: '3e tour',
    number: 3,
  },
  {
    id: 5034,
    name: '4e tour',
    number: 4,
  },
  {
    id: 5016,
    name: 'Quart de finale',
    number: 5,
  },
  {
    id: 5150,
    name: 'Demi-finale',
    number: 6,
  },
  {
    id: 5088,
    name: 'Finale',
    number: 7,
  },
];

export const doubleMatches = [
  {
    id: 123451,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 1,
    data: {
      topTeam: {
        playerOneName: 'GABRIELA DABROWSKI',
        playerTwoName: 'EDOARD ROGER-VASELLIN',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: null, tie: null },
        ],
        hasWon: null,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'LATISHA CHAN',
        playerTwoName: 'SANTIEGO GONZÁLEZ',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: null, tie: null },
        ],
        hasWon: null,
        isServing: true,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123452,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 1,
    data: {
      topTeam: {
        playerOneName: 'G.DABROWSKI',
        playerTwoName: 'E.ROGER-VASELLIN',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: null, tie: null },
        ],
        hasWon: null,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'L.CHAN',
        playerTwoName: 'S.GONZÁLEZ',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: null, tie: null },
        ],
        hasWon: null,
        isServing: true,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123453,
    round: 1,
    matchUrl: 'https://eurosport.com',
    hasWon: false,
    data: {
      topTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'Rahman MAKSSOUD',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: null, tie: null },
        ],
        hasWon: null,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'DAVIDOVICH FOKINA',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: null, tie: null },
        ],
        hasWon: null,
        isServing: true,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123454,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 1,
    data: {
      topTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'Rahman MAKSSOUD',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: null, tie: null },
        ],
        hasWon: null,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'DAVIDOVICH FOKINA',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: null, tie: null },
        ],
        hasWon: null,
        isServing: true,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123451,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 1,
    data: {
      topTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'Rahman MAKSSOUD',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: null, tie: null },
        ],
        hasWon: null,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'DAVIDOVICH FOKINA',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: null, tie: null },
        ],
        hasWon: null,
        isServing: true,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123452,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 1,
    data: {
      topTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'Rahman MAKSSOUD',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: null, tie: null },
        ],
        hasWon: null,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'DAVIDOVICH FOKINA',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: null, tie: null },
        ],
        hasWon: null,
        isServing: true,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123453,
    round: 1,
    matchUrl: 'https://eurosport.com',
    hasWon: false,
    data: {
      topTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'Rahman MAKSSOUD',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: null, tie: null },
        ],
        hasWon: null,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'DAVIDOVICH FOKINA',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: null, tie: null },
        ],
        hasWon: null,
        isServing: true,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123454,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 1,
    data: {
      topTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'Rahman MAKSSOUD',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: null, tie: null },
        ],
        hasWon: null,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'DAVIDOVICH FOKINA',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: null, tie: null },
        ],
        hasWon: null,
        isServing: true,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123455,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 2,
    data: {
      topTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'Rahman MAKSSOUD',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: null, tie: null },
        ],
        hasWon: null,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'DAVIDOVICH FOKINA',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: null, tie: null },
        ],
        hasWon: null,
        isServing: true,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123455,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 2,
    data: {
      topTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'Rahman MAKSSOUD',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: null, tie: null },
        ],
        hasWon: null,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'DAVIDOVICH FOKINA',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: null, tie: null },
        ],
        hasWon: null,
        isServing: true,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123455,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 2,
    data: {
      topTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'Rahman MAKSSOUD',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: null, tie: null },
        ],
        hasWon: null,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'DAVIDOVICH FOKINA',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: null, tie: null },
        ],
        hasWon: null,
        isServing: true,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123455,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 2,
    data: {
      topTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'Rahman MAKSSOUD',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: null, tie: null },
        ],
        hasWon: null,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'DAVIDOVICH FOKINA',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: null, tie: null },
        ],
        hasWon: null,
        isServing: true,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },

  {
    id: 123455,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 3,
    data: {
      topTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'Rahman MAKSSOUD',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: null, tie: null },
        ],
        hasWon: null,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'DAVIDOVICH FOKINA',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: null, tie: null },
        ],
        hasWon: null,
        isServing: true,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123455,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 3,
    data: {
      topTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'Rahman MAKSSOUD',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: null, tie: null },
        ],
        hasWon: null,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'DAVIDOVICH FOKINA',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: null, tie: null },
        ],
        hasWon: null,
        isServing: true,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123455,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 4,
    data: {
      topTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'Rahman MAKSSOUD',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: null, tie: null },
        ],
        hasWon: null,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'MENENDEZ-MACEIRAS',
        playerTwoName: 'DAVIDOVICH FOKINA',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: null, tie: null },
        ],
        hasWon: null,
        isServing: true,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
];

export const matches = [
  {
    id: 123451,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 1,
    data: {
      topTeam: {
        playerOneName: 'Nadal',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: false, tie: null },
        ],
        hasWon: true,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'Federer',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: true, tie: null },
        ],
        hasWon: false,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123452,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 1,
    data: {
      topTeam: {
        playerOneName: 'Nadal',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: false, tie: null },
        ],
        hasWon: true,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'Federer',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: true, tie: null },
        ],
        hasWon: false,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123453,
    round: 1,
    matchUrl: 'https://eurosport.com',
    hasWon: false,
    data: {
      topTeam: {
        playerOneName: 'Nadal',
        sets: [
          { set: 1, score: 6, won: false, tie: null },
          { set: 2, score: 2, won: false, tie: null },
          { set: 3, score: 3, won: false, tie: null },
        ],
        hasWon: false,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'Federer',
        sets: [
          { set: 1, score: 7, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: true, tie: null },
        ],
        hasWon: true,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123454,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 1,
    data: {
      topTeam: {
        playerOneName: 'Nadal',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: false, tie: null },
        ],
        hasWon: true,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'Federer',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: true, tie: null },
        ],
        hasWon: false,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123451,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 1,
    data: {
      topTeam: {
        playerOneName: 'Nadal',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: false, tie: null },
        ],
        hasWon: true,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'Federer',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: true, tie: null },
        ],
        hasWon: false,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123452,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 1,
    data: {
      topTeam: {
        playerOneName: 'Nadal',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: false, tie: null },
        ],
        hasWon: true,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'Federer',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: true, tie: null },
        ],
        hasWon: false,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123453,
    round: 1,
    matchUrl: 'https://eurosport.com',
    hasWon: false,
    data: {
      topTeam: {
        playerOneName: 'Nadal',
        sets: [
          { set: 1, score: 6, won: false, tie: null },
          { set: 2, score: 2, won: false, tie: null },
          { set: 3, score: 3, won: false, tie: null },
        ],
        hasWon: false,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'Federer',
        sets: [
          { set: 1, score: 7, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: true, tie: null },
        ],
        hasWon: true,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123454,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 1,
    data: {
      topTeam: {
        playerOneName: 'Nadal',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: false, tie: null },
        ],
        hasWon: true,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'Federer',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: true, tie: null },
        ],
        hasWon: false,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123455,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 2,
    data: {
      topTeam: {
        playerOneName: 'Nadal',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: false, tie: null },
        ],
        hasWon: true,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'Federer',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: true, tie: null },
        ],
        hasWon: false,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123455,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 2,
    data: {
      topTeam: {
        playerOneName: 'Nadal',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: false, tie: null },
        ],
        hasWon: true,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'Federer',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: true, tie: null },
        ],
        hasWon: false,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123455,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 2,
    data: {
      topTeam: {
        playerOneName: 'Nadal',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: false, tie: null },
        ],
        hasWon: true,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'Federer',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: true, tie: null },
        ],
        hasWon: false,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123455,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 2,
    data: {
      topTeam: {
        playerOneName: 'Nadal',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: false, tie: null },
        ],
        hasWon: true,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'Federer',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: true, tie: null },
        ],
        hasWon: false,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },

  {
    id: 123455,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 3,
    data: {
      topTeam: {
        playerOneName: 'Nadal',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: false, tie: null },
        ],
        hasWon: true,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'Federer',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: true, tie: null },
        ],
        hasWon: false,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123455,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 3,
    data: {
      topTeam: {
        playerOneName: 'Nadal',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: false, tie: null },
        ],
        hasWon: true,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'Federer',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: true, tie: null },
        ],
        hasWon: false,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
  {
    id: 123455,
    matchUrl: 'https://eurosport.com',
    hasWon: true,
    round: 4,
    data: {
      topTeam: {
        playerOneName: 'Nadal',
        sets: [
          { set: 1, score: 6, won: true, tie: null },
          { set: 2, score: 6, won: true, tie: null },
          { set: 3, score: 6, won: false, tie: 2 },
          { set: 4, score: 6, won: true, tie: null },
          { set: 5, score: 3, won: false, tie: null },
        ],
        hasWon: true,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
      bottomTeam: {
        playerOneName: 'Federer',
        sets: [
          { set: 1, score: 3, won: false, tie: null },
          { set: 2, score: 3, won: true, tie: null },
          { set: 3, score: 7, won: true, tie: 7 },
          { set: 4, score: 3, won: false, tie: null },
          { set: 5, score: 6, won: true, tie: null },
        ],
        hasWon: false,
        isServing: false,
        playerOneImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2202.png',
        playerTwoImage: 'https://i.eurosport.com/_iss_/geo/country/flag/small/2231.png',
      },
    },
  },
];
